/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EdicionClienteDialog.java
 *
 * Created on 9/04/2009, 07:14:39 PM
 */

package com.pmarlen.client.view;

import com.pmarlen.client.ApplicationInfo;
import java.awt.Dialog;
import java.awt.Window;

/**
 *
 * @author alfred
 */
public class EdicionClienteDialog extends javax.swing.JDialog {

    /** Creates new form EdicionClienteDialog */
    public EdicionClienteDialog(Window f) {
        super(f,Dialog.ModalityType.DOCUMENT_MODAL);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        razonSocial = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        calle = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        noExterior = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        noInterior = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        codigoPostal = new javax.swing.JTextField();
        btnBuscarPoblacion = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        delegacionOMunicipio = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        entidadFederativa = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        telefonos = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        observaciones = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_TITLE")); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));
        getContentPane().add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(11, 1, 0, 2));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_CLIENTE")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel3.add(jLabel1);

        razonSocial.setColumns(35);
        jPanel3.add(razonSocial);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_RFC")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel4.add(jLabel2);

        rfc.setColumns(12);
        jPanel4.add(rfc);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_CALLE")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel5.add(jLabel3);

        calle.setColumns(25);
        jPanel5.add(calle);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_NOEXT")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel6.add(jLabel4);

        noExterior.setColumns(8);
        jPanel6.add(noExterior);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_NOINT")); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel7.add(jLabel5);

        noInterior.setColumns(8);
        jPanel7.add(noInterior);

        jPanel1.add(jPanel7);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_POB")); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel11.add(jLabel9);

        direccion.setColumns(25);
        direccion.setEditable(false);
        direccion.setEnabled(false);
        direccion.setFocusable(false);
        jPanel11.add(direccion);

        jLabel6.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_CP")); // NOI18N
        jPanel11.add(jLabel6);

        codigoPostal.setColumns(4);
        jPanel11.add(codigoPostal);

        btnBuscarPoblacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buscar_cp_20x20.png"))); // NOI18N
        btnBuscarPoblacion.setToolTipText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_SEARCHCP")); // NOI18N
        jPanel11.add(btnBuscarPoblacion);

        jPanel1.add(jPanel11);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_MPIO")); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel8.add(jLabel7);

        delegacionOMunicipio.setColumns(25);
        delegacionOMunicipio.setEditable(false);
        delegacionOMunicipio.setEnabled(false);
        delegacionOMunicipio.setFocusable(false);
        jPanel8.add(delegacionOMunicipio);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Entidad Federativa :");
        jLabel8.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel9.add(jLabel8);

        entidadFederativa.setColumns(25);
        entidadFederativa.setEditable(false);
        entidadFederativa.setEnabled(false);
        entidadFederativa.setFocusable(false);
        jPanel9.add(entidadFederativa);

        jPanel1.add(jPanel9);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_TEL")); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel12.add(jLabel10);

        telefonos.setColumns(20);
        jPanel12.add(telefonos);

        jPanel1.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_MAIL")); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel13.add(jLabel11);

        email.setColumns(20);
        jPanel13.add(email);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_COMMENT")); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel14.add(jLabel12);

        observaciones.setColumns(35);
        jPanel14.add(observaciones);

        jPanel1.add(jPanel14);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        guardar.setText(ApplicationInfo.getLocalizedMessage("SAVE")); // NOI18N
        jPanel2.add(guardar);

        cancelar.setText(ApplicationInfo.getLocalizedMessage("CANCELL")); // NOI18N
        jPanel2.add(cancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPoblacion;
    private javax.swing.JTextField calle;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField delegacionOMunicipio;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JTextField entidadFederativa;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField noExterior;
    private javax.swing.JTextField noInterior;
    private javax.swing.JTextField observaciones;
    private javax.swing.JTextField razonSocial;
    private javax.swing.JTextField rfc;
    private javax.swing.JTextField telefonos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the calle
     */
    public javax.swing.JTextField getCalle() {
        return calle;
    }

    /**
     * @return the cancelar
     */
    public javax.swing.JButton getCancelar() {
        return cancelar;
    }

    /**
     * @return the comentarios
     */
    public javax.swing.JTextField getComentarios() {
        return observaciones;
    }

    /**
     * @return the email
     */
    public javax.swing.JTextField getEmail() {
        return email;
    }


    /**
     * @return the guardar
     */
    public javax.swing.JButton getGuardar() {
        return guardar;
    }

    /**
     * @return the noExterior
     */
    public javax.swing.JTextField getNoExterior() {
        return noExterior;
    }

    /**
     * @return the noInterior
     */
    public javax.swing.JTextField getNoInterior() {
        return noInterior;
    }


    /**
     * @return the razonSocial
     */
    public javax.swing.JTextField getRazonSocial() {
        return razonSocial;
    }

    /**
     * @return the rfc
     */
    public javax.swing.JTextField getRfc() {
        return rfc;
    }

    /**
     * @return the telefonos
     */
    public javax.swing.JTextField getTelefonos() {
        return telefonos;
    }


    /**
     * @return the observaciones
     */
    public javax.swing.JTextField getObservaciones() {
        return observaciones;
    }

	/**
	 * @return the direccion
	 */
	public javax.swing.JTextField getDireccion() {
		return direccion;
	}

    /**
     * @return the btnBuscarPoblacion
     */
    public javax.swing.JButton getBtnBuscarPoblacion() {
        return btnBuscarPoblacion;
    }

	/**
	 * @return the codigoPostal
	 */
	public javax.swing.JTextField getCodigoPostal() {
		return codigoPostal;
	}

	/**
	 * @return the delegacionOMunicipio
	 */
	public javax.swing.JTextField getDelegacionOMunicipio() {
		return delegacionOMunicipio;
	}

	/**
	 * @return the entidadFederativa
	 */
	public javax.swing.JTextField getEntidadFederativa() {
		return entidadFederativa;
	}

}
