/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pmarlen.client.view;

import com.pmarlen.client.ApplicationInfo;
import java.awt.Dialog;
import java.awt.Window;

/**
 *
 * @author alfredo
 */
public class PoblacionFinderDialog extends javax.swing.JDialog {

    /**
     * Creates new form PoblacionFinderDialog
     */
    
    public PoblacionFinderDialog(Window f) {
        super(f,Dialog.ModalityType.DOCUMENT_MODAL);
        initComponents();
        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entidadFederativa = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        delegacionOMunicipio = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigoPostal = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        poblacion = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ApplicationInfo.getLocalizedMessage("DLG_POBLACION_FINDER_TITLE")); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 2));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_ESTADO")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel3.add(jLabel1);
        jPanel3.add(entidadFederativa);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_MPIO")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel4.add(jLabel2);
        jPanel4.add(delegacionOMunicipio);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_CP")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel5.add(jLabel3);
        jPanel5.add(codigoPostal);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(ApplicationInfo.getLocalizedMessage("DLG_EDIT_CLEINTE_POB")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 18));
        jPanel6.add(jLabel4);
        jPanel6.add(poblacion);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        aceptar.setText(ApplicationInfo.getLocalizedMessage("ACCEPT")); // NOI18N
        jPanel2.add(aceptar);

        cancelar.setText(ApplicationInfo.getLocalizedMessage("CANCELL")); // NOI18N
        jPanel2.add(cancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-702)/2, (screenSize.height-227)/2, 702, 227);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox codigoPostal;
    private javax.swing.JComboBox delegacionOMunicipio;
    private javax.swing.JComboBox entidadFederativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox poblacion;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the btnAceptar
	 */
	public javax.swing.JButton getAceptar() {
		return aceptar;
	}

	/**
	 * @return the btnCancelar
	 */
	public javax.swing.JButton getCancelar() {
		return cancelar;
	}

	/**
	 * @return the codigoPostal
	 */
	public javax.swing.JComboBox getCodigoPostal() {
		return codigoPostal;
	}

	/**
	 * @return the delegacionOMunicipio
	 */
	public javax.swing.JComboBox getDelegacionOMunicipio() {
		return delegacionOMunicipio;
	}

	/**
	 * @return the entidadFederativa
	 */
	public javax.swing.JComboBox getEntidadFederativa() {
		return entidadFederativa;
	}

	/**
	 * @return the poblacion
	 */
	public javax.swing.JComboBox getPoblacion() {
		return poblacion;
	}
}
