/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalForm.java
 *
 * Created on 29/03/2009, 12:19:00 PM
 */
package com.pmarlen.client.view;

import com.pmarlen.client.ApplicationInfo;
import com.pmarlen.client.BusinessException;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author alfred
 */
public class PrincipalForm extends javax.swing.JFrame {

    private Color defaultSelectionBackground;

    /** Creates new form PrincipalForm */
    public PrincipalForm() {
        initComponents();
        defaultSelectionBackground = detallePedidoTable.getSelectionBackground();
        detallePedidoTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        try {
            setTitle(ApplicationInfo.getLocalizedMessage("APP_TITLE") + ApplicationInfo.getInstance().getVersion());
        } catch (BusinessException ex) {
            ex.printStackTrace();
        }
    }

    public List<Image> getResourcesIconImages() {
        List<Image> imgs = new ArrayList<Image>();
        try {
            imgs.add(ImageIO.read(getClass().getResourceAsStream("/imgs/Logo_1.png")));
            imgs.add(ImageIO.read(getClass().getResourceAsStream("/imgs/pmarlen_icono_2.png")));
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        return imgs;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        visorDeMarcaPorLinea = new VisorDeMarcasPanel();
        visorDeMarcaPorEmpresa = new VisorDeMarcasPanel();
        visorDePedidoActual = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallePedidoTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        esFiscal = new javax.swing.JCheckBox();
        tax = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cliente = new javax.swing.JComboBox();
        nuevoClienteAComboBox = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        formaDePago = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        procederPedidoBtn = new javax.swing.JButton();
        reiniciarPedidoBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        nombreBuscar = new javax.swing.JTextField();
        productoCBEncontrados = new javax.swing.JComboBox();
        cantidadPedida = new javax.swing.JTextField();
        atributosProductoSeleccionadoPanel = new VisorDeAtributosProductosPanel2();
        visorDePedidosGuardados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedidosGuardadosTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        enviarPedidosBtn = new javax.swing.JButton();
        visorDeClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        nuevoClienteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        viewPedidosMenu = new javax.swing.JMenuItem();
        viewClientesMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        exitMenu = new javax.swing.JMenuItem();
        sellingMenu = new javax.swing.JMenu();
        viewCatLineaMenu = new javax.swing.JMenuItem();
        viewCatEmpresaMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu3 = new javax.swing.JMenu();
        addProductoMenu = new javax.swing.JMenuItem();
        addCajaMenu = new javax.swing.JMenuItem();
        viewDetailMenu = new javax.swing.JMenuItem();
        deleteItemPedidoMenu = new javax.swing.JMenuItem();
        avoidPedidoMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutDeMenu = new javax.swing.JMenuItem();
        referenceMenu = new javax.swing.JMenuItem();
        zoomMenu = new javax.swing.JMenuItem();
        testPrintMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(getResourcesIconImages());
        setMinimumSize(new java.awt.Dimension(650, 500));

        cardPanel.setPreferredSize(new java.awt.Dimension(550, 420));
        cardPanel.setLayout(new java.awt.CardLayout());

        defaultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        defaultPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/splash_2.png"))); // NOI18N
        defaultPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        cardPanel.add(defaultPanel, "defaultPanel");

        visorDeMarcaPorLinea.setBorder(javax.swing.BorderFactory.createTitledBorder(ApplicationInfo.getLocalizedMessage("APP_MENU_CAT_LINEA"))); // NOI18N
        cardPanel.add(visorDeMarcaPorLinea, "visorDeMarcaPorLinea");

        visorDeMarcaPorEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(ApplicationInfo.getLocalizedMessage("APP_MENU_CAT_EMPRESA"))); // NOI18N
        cardPanel.add(visorDeMarcaPorEmpresa, "visorDeMarcaPorEmpresa");

        visorDePedidoActual.setBorder(javax.swing.BorderFactory.createTitledBorder(ApplicationInfo.getLocalizedMessage("APP_MENU_DETAIL_PEDIDO"))); // NOI18N
        visorDePedidoActual.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 220));

        detallePedidoTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                detallePedidoTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                detallePedidoTableFocusLost(evt);
            }
        });
        detallePedidoTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detallePedidoTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(detallePedidoTable);

        visorDePedidoActual.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(256, 190));
        jPanel1.setLayout(new java.awt.GridLayout(7, 1, 5, 2));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jLabel7.setText(ApplicationInfo.getLocalizedMessage("LBL_PEDIDO_SUBTOTAL")); // NOI18N
        jPanel11.add(jLabel7);

        subtotal.setColumns(10);
        subtotal.setEditable(false);
        subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        subtotal.setFocusable(false);
        jPanel11.add(subtotal);

        jPanel1.add(jPanel11);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jLabel5.setText(ApplicationInfo.getLocalizedMessage("LBL_PEDIDO_DISCOUNT")); // NOI18N
        jPanel9.add(jLabel5);

        discount.setColumns(10);
        discount.setEditable(false);
        discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discount.setFocusable(false);
        jPanel9.add(discount);

        jPanel1.add(jPanel9);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        esFiscal.setText(ApplicationInfo.getLocalizedMessage("LBL_PEDIDO_TAX")); // NOI18N
        esFiscal.setToolTipText("Al marcar Si Aplica I.V.A. se cambia el modo Fisca: Factura / Nota");
        jPanel8.add(esFiscal);

        tax.setColumns(10);
        tax.setEditable(false);
        tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tax.setFocusable(false);
        jPanel8.add(tax);

        jPanel1.add(jPanel8);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(ApplicationInfo.getLocalizedMessage("LBL_PEDIDO_TOTAL")); // NOI18N
        jPanel10.add(jLabel6);

        total.setColumns(10);
        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 1, 11));
        total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total.setFocusable(false);
        jPanel10.add(total);

        jPanel1.add(jPanel10);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(ApplicationInfo.getLocalizedMessage("LABEL_CLIENTE")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 18));
        jPanel3.add(jLabel2);
        jPanel3.add(cliente);

        nuevoClienteAComboBox.setText(ApplicationInfo.getLocalizedMessage("LABEL_NEWCLIENTE")); // NOI18N
        jPanel3.add(nuevoClienteAComboBox);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(ApplicationInfo.getLocalizedMessage("LABEL_FORMADEPAGO")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 18));
        jPanel4.add(jLabel3);
        jPanel4.add(formaDePago);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        procederPedidoBtn.setText(ApplicationInfo.getLocalizedMessage("LABEL_PROCED")); // NOI18N
        jPanel6.add(procederPedidoBtn);

        reiniciarPedidoBtn.setText(ApplicationInfo.getLocalizedMessage("LABEL_RESET")); // NOI18N
        jPanel6.add(reiniciarPedidoBtn);

        jPanel1.add(jPanel6);

        visorDePedidoActual.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nombreBuscar.setColumns(15);
        jPanel14.add(nombreBuscar);

        productoCBEncontrados.setMinimumSize(new java.awt.Dimension(350, 22));
        productoCBEncontrados.setPreferredSize(new java.awt.Dimension(350, 22));
        jPanel14.add(productoCBEncontrados);

        cantidadPedida.setColumns(4);
        cantidadPedida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel14.add(cantidadPedida);

        jPanel13.add(jPanel14, java.awt.BorderLayout.NORTH);

        atributosProductoSeleccionadoPanel.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel13.add(atributosProductoSeleccionadoPanel, java.awt.BorderLayout.CENTER);

        visorDePedidoActual.add(jPanel13, java.awt.BorderLayout.NORTH);

        cardPanel.add(visorDePedidoActual, "visorDePedidoActual");

        visorDePedidosGuardados.setBorder(javax.swing.BorderFactory.createTitledBorder(ApplicationInfo.getLocalizedMessage("APP_MENU_VIEW_PEDIDOS"))); // NOI18N
        visorDePedidosGuardados.setLayout(new java.awt.BorderLayout());

        pedidosGuardadosTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pedidosGuardadosTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pedidosGuardadosTableFocusLost(evt);
            }
        });
        pedidosGuardadosTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pedidosGuardadosTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(pedidosGuardadosTable);

        visorDePedidosGuardados.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        enviarPedidosBtn.setText(ApplicationInfo.getLocalizedMessage("SEND_ALL_PEDIDOS")); // NOI18N
        jPanel5.add(enviarPedidosBtn);

        visorDePedidosGuardados.add(jPanel5, java.awt.BorderLayout.SOUTH);

        cardPanel.add(visorDePedidosGuardados, "visorDePedidosGuardados");

        visorDeClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(ApplicationInfo.getLocalizedMessage("APP_MENU_VIEW_CLIENTES"))); // NOI18N
        visorDeClientes.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane .HORIZONTAL_SCROLLBAR_ALWAYS);

        clientesTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        clientesTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientesTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientesTableFocusLost(evt);
            }
        });
        clientesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientesTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(clientesTable);

        visorDeClientes.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nuevoClienteBtn.setText(ApplicationInfo.getLocalizedMessage("LABEL_NEWCLIENTE")); // NOI18N
        jPanel7.add(nuevoClienteBtn);

        visorDeClientes.add(jPanel7, java.awt.BorderLayout.SOUTH);

        cardPanel.add(visorDeClientes, "visorDeClientes");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 1, 1));

        label1.setText(" ");
        label1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(label1);

        label2.setText(" ");
        label2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(label2);

        label3.setText(" ");
        label3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(label3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        fileMenu.setMnemonic(ApplicationInfo.getLocalizedMessage("APP_MENU_ACCLERATOR_FILE").charAt(0));
        fileMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_FILE")); // NOI18N

        viewPedidosMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        viewPedidosMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_VIEW_PEDIDOS")); // NOI18N
        fileMenu.add(viewPedidosMenu);

        viewClientesMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        viewClientesMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_VIEW_CLIENTES")); // NOI18N
        fileMenu.add(viewClientesMenu);
        fileMenu.add(jSeparator2);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_EXIT")); // NOI18N
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        sellingMenu.setMnemonic(ApplicationInfo.getLocalizedMessage("APP_MENU_ACCLERATOR_SALE").charAt(0));
        sellingMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_SALE")); // NOI18N

        viewCatLineaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        viewCatLineaMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_CAT_LINEA")); // NOI18N
        sellingMenu.add(viewCatLineaMenu);

        viewCatEmpresaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        viewCatEmpresaMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_CAT_EMPRESA")); // NOI18N
        sellingMenu.add(viewCatEmpresaMenu);
        sellingMenu.add(jSeparator1);

        jMenu3.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_PEDIDO")); // NOI18N

        addProductoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        addProductoMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_ADD_PRODUCTO")); // NOI18N
        jMenu3.add(addProductoMenu);

        addCajaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        addCajaMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_ADD_CAJA_PRODUCTO")); // NOI18N
        jMenu3.add(addCajaMenu);

        viewDetailMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        viewDetailMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_DETAIL_PEDIDO")); // NOI18N
        jMenu3.add(viewDetailMenu);

        deleteItemPedidoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        deleteItemPedidoMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_DELTE_PEDIDOITEM")); // NOI18N
        jMenu3.add(deleteItemPedidoMenu);

        avoidPedidoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_MASK));
        avoidPedidoMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_AVOID_PEDIDO")); // NOI18N
        jMenu3.add(avoidPedidoMenu);

        sellingMenu.add(jMenu3);

        jMenuBar1.add(sellingMenu);

        helpMenu.setMnemonic(ApplicationInfo.getLocalizedMessage("APP_MENU_ACCLERATOR_HELP").charAt(0));
        helpMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_HELP")); // NOI18N

        aboutDeMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_ABOUT")); // NOI18N
        helpMenu.add(aboutDeMenu);

        referenceMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        referenceMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_REFERENCE")); // NOI18N
        helpMenu.add(referenceMenu);

        zoomMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        zoomMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_ZOOM")); // NOI18N
        helpMenu.add(zoomMenu);

        testPrintMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        testPrintMenu.setText(ApplicationInfo.getLocalizedMessage("APP_MENU_TEST_PRINT")); // NOI18N
        helpMenu.add(testPrintMenu);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detallePedidoTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detallePedidoTableFocusGained
        detallePedidoTable.setSelectionBackground(Color.GREEN);
    }//GEN-LAST:event_detallePedidoTableFocusGained

    private void detallePedidoTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detallePedidoTableFocusLost
        detallePedidoTable.setSelectionBackground(defaultSelectionBackground);
    }//GEN-LAST:event_detallePedidoTableFocusLost

    private void detallePedidoTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detallePedidoTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            evt.consume();
            detallePedidoTable.transferFocus();
        }
    }//GEN-LAST:event_detallePedidoTableKeyPressed

    private void pedidosGuardadosTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pedidosGuardadosTableFocusGained
        pedidosGuardadosTable.setSelectionBackground(Color.GREEN);
    }//GEN-LAST:event_pedidosGuardadosTableFocusGained

    private void pedidosGuardadosTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pedidosGuardadosTableFocusLost
        pedidosGuardadosTable.setSelectionBackground(defaultSelectionBackground);
    }//GEN-LAST:event_pedidosGuardadosTableFocusLost

    private void pedidosGuardadosTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pedidosGuardadosTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            evt.consume();
            pedidosGuardadosTable.transferFocus();
        }
    }//GEN-LAST:event_pedidosGuardadosTableKeyPressed

    private void clientesTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientesTableFocusGained
        clientesTable.setSelectionBackground(Color.GREEN);
    }//GEN-LAST:event_clientesTableFocusGained

    private void clientesTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientesTableFocusLost
        clientesTable.setSelectionBackground(defaultSelectionBackground);
    }//GEN-LAST:event_clientesTableFocusLost

    private void clientesTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientesTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            evt.consume();
            clientesTable.transferFocus();
        }
    }//GEN-LAST:event_clientesTableKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutDeMenu;
    private javax.swing.JMenuItem addCajaMenu;
    private javax.swing.JMenuItem addProductoMenu;
    private javax.swing.JPanel atributosProductoSeleccionadoPanel;
    private javax.swing.JMenuItem avoidPedidoMenu;
    private javax.swing.JTextField cantidadPedida;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JComboBox cliente;
    private javax.swing.JTable clientesTable;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JMenuItem deleteItemPedidoMenu;
    private javax.swing.JTable detallePedidoTable;
    private javax.swing.JTextField discount;
    private javax.swing.JButton enviarPedidosBtn;
    private javax.swing.JCheckBox esFiscal;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox formaDePago;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField nombreBuscar;
    private javax.swing.JButton nuevoClienteAComboBox;
    private javax.swing.JButton nuevoClienteBtn;
    private javax.swing.JTable pedidosGuardadosTable;
    private javax.swing.JButton procederPedidoBtn;
    private javax.swing.JComboBox productoCBEncontrados;
    private javax.swing.JMenuItem referenceMenu;
    private javax.swing.JButton reiniciarPedidoBtn;
    private javax.swing.JMenu sellingMenu;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JMenuItem testPrintMenu;
    private javax.swing.JTextField total;
    private javax.swing.JMenuItem viewCatEmpresaMenu;
    private javax.swing.JMenuItem viewCatLineaMenu;
    private javax.swing.JMenuItem viewClientesMenu;
    private javax.swing.JMenuItem viewDetailMenu;
    private javax.swing.JMenuItem viewPedidosMenu;
    private javax.swing.JPanel visorDeClientes;
    private javax.swing.JPanel visorDeMarcaPorEmpresa;
    private javax.swing.JPanel visorDeMarcaPorLinea;
    private javax.swing.JPanel visorDePedidoActual;
    private javax.swing.JPanel visorDePedidosGuardados;
    private javax.swing.JMenuItem zoomMenu;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the aboutDeMenu
     */
    public javax.swing.JMenuItem getAboutDeMenu() {
        return aboutDeMenu;
    }

    /**
     * @return the addCajaMenu
     */
    public javax.swing.JMenuItem getAddCajaMenu() {
        return addCajaMenu;
    }

    /**
     * @return the addProductoMenu
     */
    public javax.swing.JMenuItem getAddProductoMenu() {
        return addProductoMenu;
    }

    /**
     * @return the avoidPedidoMenu
     */
    public javax.swing.JMenuItem getAvoidPedidoMenu() {
        return avoidPedidoMenu;
    }

    /**
     * @return the cardPanel
     */
    public javax.swing.JPanel getCardPanel() {
        return cardPanel;
    }

    /**
     * @return the defaultPanel
     */
    public javax.swing.JPanel getDefaultPanel() {
        return defaultPanel;
    }

    /**
     * @return the exitMenu
     */
    public javax.swing.JMenuItem getExitMenu() {
        return exitMenu;
    }

    /**
     * @return the label1
     */
    public javax.swing.JLabel getLabel1() {
        return label1;
    }

    /**
     * @return the label2
     */
    public javax.swing.JLabel getLabel2() {
        return label2;
    }

    /**
     * @return the label3
     */
    public javax.swing.JLabel getLabel3() {
        return label3;
    }

    /**
     * @return the referenceMenu
     */
    public javax.swing.JMenuItem getReferenceMenu() {
        return referenceMenu;
    }

    /**
     * @return the testPrintMenu
     */
    public javax.swing.JMenuItem getTestPrintMenu() {
        return testPrintMenu;
    }

    /**
     * @return the viewCatEmpresaMenu
     */
    public javax.swing.JMenuItem getViewCatEmpresaMenu() {
        return viewCatEmpresaMenu;
    }

    /**
     * @return the viewCatLineaMenu
     */
    public javax.swing.JMenuItem getViewCatLineaMenu() {
        return viewCatLineaMenu;
    }

    /**
     * @return the viewDetailMenu
     */
    public javax.swing.JMenuItem getViewDetailMenu() {
        return viewDetailMenu;
    }

    /**
     * @return the zoomMenu
     */
    public javax.swing.JMenuItem getZoomMenu() {
        return zoomMenu;
    }

    /**
     * @return the visorDeMarcaPorEmpresa
     */
    public javax.swing.JPanel getVisorDeMarcaPorEmpresa() {
        return visorDeMarcaPorEmpresa;
    }

    /**
     * @return the visorDeMarcaPorLinea
     */
    public javax.swing.JPanel getVisorDeMarcaPorLinea() {
        return visorDeMarcaPorLinea;
    }

    /**
     * @return the cliente
     */
    public javax.swing.JComboBox getCliente() {
        return cliente;
    }

    /**
     * @return the detallePedidoTable
     */
    public javax.swing.JTable getDetallePedidoTable() {
        return detallePedidoTable;
    }

    /**
     * @return the formaDePago
     */
    public javax.swing.JComboBox getFormaDePago() {
        return formaDePago;
    }

    /**
     * @return the procederPedidoBtn
     */
    public javax.swing.JButton getProcederPedidoBtn() {
        return procederPedidoBtn;
    }

    /**
     * @return the reiniciarPedidoBtn
     */
    public javax.swing.JButton getReiniciarPedidoBtn() {
        return reiniciarPedidoBtn;
    }

    /**
     * @return the enviarPedidosBtn
     */
    public javax.swing.JButton getEnviarPedidosBtn() {
        return enviarPedidosBtn;
    }

    /**
     * @return the pedidosGuardadosTable
     */
    public javax.swing.JTable getPedidosGuardadosTable() {
        return pedidosGuardadosTable;
    }

    /**
     * @return the viewClientesMenu
     */
    public javax.swing.JMenuItem getViewClientesMenu() {
        return viewClientesMenu;
    }

    /**
     * @return the viewPedidosMenu
     */
    public javax.swing.JMenuItem getViewPedidosMenu() {
        return viewPedidosMenu;
    }

    /**
     * @return the visorDeClientes
     */
    public javax.swing.JPanel getVisorDeClientes() {
        return visorDeClientes;
    }

    /**
     * @return the visorDePedidoActual
     */
    public javax.swing.JPanel getVisorDePedidoActual() {
        return visorDePedidoActual;
    }

    /**
     * @return the visorDePedidosGuardados
     */
    public javax.swing.JPanel getVisorDePedidosGuardados() {
        return visorDePedidosGuardados;
    }

    /**
     * @return the deleteItemPedidoMenu
     */
    public javax.swing.JMenuItem getDeleteItemPedidoMenu() {
        return deleteItemPedidoMenu;
    }

    /**
     * @return the clientesTable
     */
    public javax.swing.JTable getClientesTable() {
        return clientesTable;
    }

    /**
     * @return the nuevoClienteBtn
     */
    public javax.swing.JButton getNuevoClienteBtn() {
        return nuevoClienteBtn;
    }

    /**
     * @return the nuevoClienteAComboBox
     */
    public javax.swing.JButton getNuevoClienteAComboBox() {
        return nuevoClienteAComboBox;
    }

    /**
     * @return the defaultSelectionBackground
     */
    public Color getDefaultSelectionBackground() {
        return defaultSelectionBackground;
    }

    /**
     * @return the discount
     */
    public javax.swing.JTextField getDiscount() {
        return discount;
    }

    /**
     * @return the esFiscal
     */
    public javax.swing.JCheckBox getEsFiscal() {
        return esFiscal;
    }

    /**
     * @return the fileMenu
     */
    public javax.swing.JMenu getFileMenu() {
        return fileMenu;
    }

    /**
     * @return the sellingMenu
     */
    public javax.swing.JMenu getSellingMenu() {
        return sellingMenu;
    }

    /**
     * @return the subtotal
     */
    public javax.swing.JTextField getSubtotal() {
        return subtotal;
    }

    /**
     * @return the tax
     */
    public javax.swing.JTextField getTax() {
        return tax;
    }

    /**
     * @return the total
     */
    public javax.swing.JTextField getTotal() {
        return total;
    }

    /**
     * @return the productoCBEncontrados
     */
    public javax.swing.JComboBox getProductoCBEncontrados() {
        return productoCBEncontrados;
    }

    /**
     * @return the nombreBuscar
     */
    public javax.swing.JTextField getNombreBuscar() {
        return nombreBuscar;
    }

    /**
     * @return the cantidadPedida
     */
    public javax.swing.JTextField getCantidadPedida() {
        return cantidadPedida;
    }

    /**
     * @return the atributosProductoSeleccionadoPanel
     */
    public javax.swing.JPanel getAtributosProductoSeleccionadoPanel() {
        return atributosProductoSeleccionadoPanel;
    }
}
