/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisorDeProductosDefaultPanel.java
 *
 * Created on 29/03/2009, 12:51:03 PM
 */

package com.pmarlen.client.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import org.springframework.stereotype.Controller;

/**
 *
 * @author alfred
 */
@Controller("visorDeProductosDefaultPanel")
public class VisorDeProductosDefaultPanel extends javax.swing.JPanel {
    Color defaultSelectionBackground;
    public static final int TABLE_PREFSIZE_WIDTH = 280;
    /** Creates new form VisorDeProductosDefaultPanel */
    public VisorDeProductosDefaultPanel() {
        initComponents();
        defaultSelectionBackground = productosDeMarcaTable.getSelectionBackground();
        KeyStroke ks = KeyStroke.getKeyStroke("ctrl a");
        productosDeMarcaTable.getInputMap().put(ks, "none");
        productosDeMarcaTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        productosDeMarcaTable.setRowSelectionAllowed(true);       
        //productosDeMarcaTable.setCellSelectionEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosDeMarcaTable = new javax.swing.JTable();
        info = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        visorDeAtributos = new VisorDeAtributosProductosPanel();
        panelDisplayer = new JPanelDisplayer();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(250, 24));
        jScrollPane1.setPreferredSize(new Dimension(TABLE_PREFSIZE_WIDTH,400));

        productosDeMarcaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        productosDeMarcaTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        productosDeMarcaTable.setRowHeight(100);
        productosDeMarcaTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productosDeMarcaTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                productosDeMarcaTableFocusLost(evt);
            }
        });
        productosDeMarcaTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productosDeMarcaTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(productosDeMarcaTable);

        add(jScrollPane1, java.awt.BorderLayout.WEST);
        add(info, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        visorDeAtributos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(visorDeAtributos, java.awt.BorderLayout.SOUTH);

        panelDisplayer.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(panelDisplayer, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void productosDeMarcaTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productosDeMarcaTableFocusGained
        productosDeMarcaTable.setSelectionBackground(Color.GREEN);
    }//GEN-LAST:event_productosDeMarcaTableFocusGained

    private void productosDeMarcaTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productosDeMarcaTableFocusLost
        productosDeMarcaTable.setSelectionBackground(defaultSelectionBackground);
    }//GEN-LAST:event_productosDeMarcaTableFocusLost

    private void productosDeMarcaTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productosDeMarcaTableKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            evt.consume();
        } else if(evt.getKeyCode() == KeyEvent.VK_TAB){
            evt.consume();
            productosDeMarcaTable.transferFocus();
        }
    }//GEN-LAST:event_productosDeMarcaTableKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDisplayer;
    private javax.swing.JTable productosDeMarcaTable;
    private javax.swing.JPanel visorDeAtributos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the productosDeMarcaTable
     */
    public javax.swing.JTable getProductosDeMarcaTable() {
        return productosDeMarcaTable;
    }

    /**
     * @return the info
     */
    public javax.swing.JLabel getInfo() {
        return info;
    }

    /**
     * @return the visorDeAtributos
     */
    public VisorDeAtributosProductosPanel getVisorDeAtributos() {
        return (VisorDeAtributosProductosPanel)visorDeAtributos;
    }
    
    public void setImageForPanelDisplayer(int selected) {
        ((JPanelDisplayer)panelDisplayer).setImageSelected(selected);
    }

    public void setAllImages(BufferedImage[] allIamges) {
        ((JPanelDisplayer)panelDisplayer).setAllImages(allIamges);
    }

}
