DELETE FROM CLIENTE_CONTACTO;
DELETE FROM PROVEEDOR_CONTACTO;
DELETE FROM CONTACTO;
DELETE FROM CLIENTE;

INSERT INTO CLIENTE VALUES 	(1,1,'ACV950717KN9',now(),'ABARROTERA COMERCIAL VALLE SA DE CV',NULL,'Nave E Bodega 518, Centra del Abastos de Ecatepec','518','s/n',100,'58370253,58371099',NULL,NULL,'art_min_2@hotmail.com',NULL,NULL,'Precio Real $255.96','Clientes Luciano');	
INSERT INTO CONTACTO(ID,FECHA_CREACION,NOMBRE,EMAIL,TELEFONOS,DIRECCION,POBLACION_ID)  VALUES 	(11,now(),'Isidro Rodráguez Blanquet','art_min_2@hotmail.com',NULL,NULL,NULL);	
INSERT INTO CLIENTE_CONTACTO VALUES 	(1,11);

INSERT INTO CLIENTE VALUES 	(2,1,'AST990216PC2',now(),'ABARROTES SANTO TOMAS SA DE CV',NULL,'Xochiatipan Lt.725, Mz.52 esq. Actopan','725','52',200,'7919135819,7919153193',NULL,NULL,'vch@prodigy.net.mx',NULL,NULL,'Precio Real $268.79','Apan-Sn Juan');	
INSERT INTO CONTACTO(ID,FECHA_CREACION,NOMBRE,EMAIL,TELEFONOS,DIRECCION,POBLACION_ID)  VALUES 	(12,now(),'Sr. Bernardo','vch@prodigy.net.mx',NULL,NULL,NULL);
INSERT INTO CLIENTE_CONTACTO VALUES 	(2,12);

INSERT INTO CLIENTE VALUES 	(3,1,'AAS030211U80',now(),'ABASTECEDORA DE ABARROTES SCORPION SA DE CV',NULL,'Nave E Bodega 506 SN, Central de Abastos de Ecatepec','s/n','s/n',100,'58369030',NULL,NULL,'dlemus@scorpion.com.mx',NULL,NULL,' ext. 1032','Clientes Luciano');	
INSERT INTO CONTACTO(ID,FECHA_CREACION,NOMBRE,EMAIL,TELEFONOS,DIRECCION,POBLACION_ID)  VALUES 	(13,now(),'Diana Lemus','dlemus@scorpion.com.mx',NULL,NULL,NULL);	
INSERT INTO CLIENTE_CONTACTO VALUES 	(3,13);

INSERT INTO CLIENTE VALUES 	(4,2,'AAFA530902BK7',now(),'ALCANTARA FUENTES AURORA MARIA DEL CONSUELO','Farmacia el Pastillero','Luis Cabrera','23','s/n',200,'7979754111',NULL,NULL,NULL,NULL,NULL,NULL,'Zacatlán-Chignahuapan');				

INSERT INTO CLIENTE VALUES 	(5,1,'ALA900710AZ4',now(),'ALMACENES LACONA SA DE CV',NULL,'Av. Reforma','2','s/n',300,'7787370616,7787370608',NULL,NULL,'lacona@lacona.com.mx',NULL,'www.lacona.com.mx','Socorro (Pagos)','Apaxco-Tequixquiac');	
INSERT INTO CONTACTO(ID,FECHA_CREACION,NOMBRE,EMAIL,TELEFONOS,DIRECCION,POBLACION_ID)  VALUES 	(14,now(),'Macario Ramárez','lacona@lacona.com.mx',NULL,NULL,NULL);	
INSERT INTO CLIENTE_CONTACTO VALUES 	(5,14);

INSERT INTO CLIENTE VALUES 	(7,1,'AAT070907A32',now(),'AZTECA ABARROTERA TM SA DE CV','AZTECA ABARROTERA TM SA DE CV','Nave B Bodega 250','250','s/n',400,'58371208',NULL,NULL,NULL,NULL,NULL,'Precio Real $257.21','Clientes Luciano');	
INSERT INTO CONTACTO(ID,FECHA_CREACION,NOMBRE,EMAIL,TELEFONOS,DIRECCION,POBLACION_ID)  VALUES 	(15,now(),'Rosy',NULL,NULL,NULL,NULL);	
INSERT INTO CLIENTE_CONTACTO VALUES 	(7,15);
